language: java

before_script:
  - cd ../
  - git clone --depth=1 https://github.com/jsdoc3/jsdoc.git jsdoc
  - mkdir jsdoc/addons
  - mv jsdoc-plugins/* jsdoc/addons/
  - cd jsdoc
  - sed "/var specFolders/ c\var specFolders = ['addons/test/specs'];" <test/runner.js >test/runner.jsnew
  - mv test/runner.jsnew test/runner.js

script:
  - "./jsdoc -T"
